from agents.base_agent import BaseAgent, AgentConfig
from typing import Dict
import random
import json
from datetime import datetime  # Add this import

class DocumentationAgent(BaseAgent):
    def __init__(self, config: AgentConfig, llm_manager, github_manager):
        super().__init__(config, llm_manager, github_manager)
        self.docs_topics = [
            "API Documentation", "Tutorial", "How-to Guide",
            "Technical Deep Dive", "Best Practices", "Troubleshooting Guide",
            "Architecture Overview", "Getting Started Guide", "User Manual",
            "Developer Guide", "Reference Documentation", "FAQ",
            "Migration Guide", "Release Notes", "Contributing Guide"
        ]
        
        self.tech_stacks = [
            "Python", "JavaScript", "React", "Docker", "Kubernetes",
            "Machine Learning", "Web Development", "Data Science",
            "FastAPI", "Django", "Flask", "Node.js", "TypeScript",
            "AWS", "Azure", "Google Cloud", "SQL", "NoSQL", "Git",
            "Linux", "Windows", "macOS", "Android", "iOS"
        ]
    
    async def generate_content(self) -> Dict[str, str]:
        """Generate documentation content"""
        
        topic = random.choice(self.docs_topics)
        tech_stack = random.choice(self.tech_stacks)
        doc_type = self.config.commit_pattern
        
        if doc_type == "api_docs":
            prompt = self._create_api_docs_prompt(topic, tech_stack)
        elif doc_type == "tutorial":
            prompt = self._create_tutorial_prompt(topic, tech_stack)
        elif doc_type == "docs_only":
            prompt = self._create_general_docs_prompt(topic, tech_stack)
        else:
            prompt = self._create_general_docs_prompt(topic, tech_stack)
        
        content = await self.llm.generate_text(
            prompt=prompt,
            system_prompt="You are an expert technical writer. Create clear, concise, and comprehensive documentation.",
            temperature=0.5
        )
        
        # Generate metadata for the documentation
        metadata = {
            "topic": topic,
            "tech_stack": tech_stack,
            "doc_type": doc_type,
            "generated_at": datetime.now().isoformat(),
            "agent_name": self.config.name
        }
        
        # Create filename
        safe_topic = topic.lower().replace(' ', '_').replace('/', '_')
        safe_tech = tech_stack.lower().replace(' ', '_').replace('/', '_')
        filename = f"docs/{safe_topic}_{safe_tech}_{random.randint(100, 999)}.md"
        
        # Add metadata header to the content
        full_content = f"""---
title: "{topic} for {tech_stack}"
description: "Auto-generated documentation on {topic.lower()} for {tech_stack}"
category: {topic}
technology: {tech_stack}
difficulty: {random.choice(['Beginner', 'Intermediate', 'Advanced'])}
author: "AI Documentation Agent"
date: {datetime.now().strftime('%Y-%m-%d')}
---

{content}

---

*This document was automatically generated by an AI agent.*
"""
        
        return {
            filename: full_content,
            f"{filename.replace('.md', '')}_metadata.json": json.dumps(metadata, indent=2)
        }
    
    def _create_api_docs_prompt(self, topic: str, tech_stack: str) -> str:
        """Create prompt for API documentation"""
        return f"""Create comprehensive API documentation for {topic} using {tech_stack}.

Include the following sections:
1. Introduction and Overview
2. Installation and Setup
3. Authentication (if applicable)
4. Available Endpoints with:
   - HTTP Method
   - URL
   - Request Parameters
   - Request Body Schema
   - Response Format
   - Status Codes
   - Example Request/Response
5. Error Handling
6. Rate Limiting
7. Best Practices
8. Common Use Cases
9. Code Examples in {tech_stack}
10. Troubleshooting

Make it practical and ready for developers to use immediately."""
    
    def _create_tutorial_prompt(self, topic: str, tech_stack: str) -> str:
        """Create prompt for tutorial documentation"""
        return f"""Create a step-by-step tutorial on {topic} using {tech_stack}.

Structure the tutorial as follows:
1. Prerequisites and Setup
2. Learning Objectives
3. Step-by-Step Instructions with:
   - Clear explanations
   - Code snippets
   - Screenshots or diagrams (describe what would be shown)
   - Expected outputs
4. Common Pitfalls and How to Avoid Them
5. Exercises for Practice
6. Further Reading and Resources
7. Summary and Key Takeaways

Make it beginner-friendly and include practical examples that readers can follow along."""
    
    def _create_general_docs_prompt(self, topic: str, tech_stack: str) -> str:
        """Create prompt for general documentation"""
        return f"""Create comprehensive documentation about {topic} for {tech_stack}.

Include:
1. Clear title and introduction explaining what this is about
2. Detailed explanations with practical examples
3. Code snippets where applicable
4. Diagrams or pseudo-code descriptions (describe what the diagram would show)
5. Common use cases and examples
6. Best practices and recommendations
7. References and further reading
8. Frequently Asked Questions (FAQ)

Format as a well-structured markdown document that is both informative and practical."""
    
    def get_commit_message(self, content: Dict[str, str]) -> str:
        """Generate commit message based on content"""
        # Get the first filename to extract topic
        first_file = list(content.keys())[0]
        
        if first_file.endswith('.json'):
            # Try to get metadata
            import json
            try:
                metadata_content = content[first_file]
                metadata = json.loads(metadata_content)
                topic = metadata.get('topic', 'Documentation')
                tech = metadata.get('tech_stack', '')
                if tech:
                    return f"Add {topic} documentation for {tech}"
                else:
                    return f"Add {topic} documentation"
            except:
                return "Add documentation files"
        
        # Extract from filename
        filename = first_file.replace('docs/', '').replace('.md', '')
        parts = filename.split('_')
        if len(parts) >= 2:
            topic = parts[0].replace('_', ' ').title()
            tech = parts[1].replace('_', ' ').title()
            return f"Add {topic} documentation for {tech}"
        
        return "Add documentation update"