import random
import json
from agents.base_agent import BaseAgent, AgentConfig
from typing import Dict

class LeetCodeAgent(BaseAgent):
    def __init__(self, config: AgentConfig, llm_manager, github_manager):
        super().__init__(config, llm_manager, github_manager)
        self.problem_categories = [
            "Array", "String", "Hash Table", "Dynamic Programming",
            "Math", "Sorting", "Greedy", "Depth-First Search",
            "Binary Search", "Database", "Breadth-First Search", "Tree",
            "Matrix", "Two Pointers", "Bit Manipulation", "Stack"
        ]
    
    async def generate_content(self) -> Dict[str, str]:
        """Generate LeetCode problem and solution"""
        
        # Generate problem
        problem_prompt = f"""Create a LeetCode-style coding problem with:
        1. Problem title
        2. Problem description with clear requirements
        3. Examples (at least 3)
        4. Constraints
        5. Difficulty: {random.choice(['Easy', 'Medium', 'Hard'])}
        6. Category: {random.choice(self.problem_categories)}
        
        Format the response as a JSON object with these keys."""
        
        problem = await self.llm.generate_text(
            prompt=problem_prompt,
            system_prompt="You are an expert at creating coding challenges.",
            temperature=0.7
        )
        
        # Generate solution
        solution_prompt = f"""Provide a solution for this problem:
        {problem}
        
        Include:
        1. Python solution with optimal time/space complexity
        2. Explanation of the approach
        3. Time and space complexity analysis
        4. Alternative solutions if applicable"""
        
        solution = await self.llm.generate_text(
            prompt=solution_prompt,
            system_prompt="You are an expert at solving coding problems.",
            temperature=0.3
        )
        
        # Generate README
        readme_content = f"""# {json.loads(problem).get('title', 'Problem')}
        
## Problem Description
{json.loads(problem).get('description', '')}

## Solution
{solution}

## Author
Auto-generated by AI Agent
"""
        
        # Create test file
        test_content = self._generate_test_code(json.loads(problem))
        
        return {
            "README.md": readme_content,
            "solution.py": self._extract_python_code(solution),
            "test_solution.py": test_content,
            f"problem_{random.randint(1000, 9999)}.json": problem
        }
    
    def _extract_python_code(self, solution_text: str) -> str:
        """Extract Python code from solution text"""
        # Simple extraction - you might want to improve this
        if "```python" in solution_text:
            code = solution_text.split("```python")[1].split("```")[0]
        elif "```" in solution_text:
            code = solution_text.split("```")[1].split("```")[0]
        else:
            code = solution_text
        return code.strip()
    
    def _generate_test_code(self, problem_data: Dict) -> str:
        """Generate test code for the problem"""
        return f'''import unittest
from solution import Solution

class TestSolution(unittest.TestCase):
    def setUp(self):
        self.solution = Solution()
    
    def test_example1(self):
        # Test case 1
        pass
    
    def test_example2(self):
        # Test case 2
        pass

if __name__ == '__main__':
    unittest.main()
'''
    
    def get_commit_message(self, content: Dict[str, str]) -> str:
        problem_title = list(content.keys())[-1].replace('.json', '')
        return f"Add {problem_title} solution"